### ISSUE TITLE
todo for first release

### ISSUE THREAD

**Issue by hmatsuda** [hmatsuda/ruby-block#1]
- [x] minibuffer
- [x] go to block starting position command
- [x] configure display options
- [x] marker should destroy on did change active pane item
- [x] goto word beginning position
- [x] activation problem fix
- [x] upload option screenshot
- [x] add bottom panel into default
- [x] write spec
